### ISSUE TITLE
flurryAnalytics not defined in JS in iOS

### ISSUE THREAD

**Issue by nitzanwilnai** [blakgeek/cordova-plugin-flurryanalytics#10]
I added the plugin cordova-plugin-flurryanalytics and it seems to have installed correctly. Unfortunately when I try to call flurryAnalytics = new FlurryAnalytics(); the variable flurryAnalytics does not exist. 

I added all the required packages and flurry is listed in the config.xml file and plugin files. 

Any ideas?

**Comment by nitzanwilnai** [comment]
Here is the output from a tiny project with only FlurryAnalytics and Audio plugins. Again, flurryAnalytics js is not defined. 

The .m is in BuildPhases -> Compile Resources. Screenshot:
https://www.dropbox.com/s/76lzp82e5zf182s/Screenshot%202016-01-21%2006.34.32.png?dl=0

And the library is there too:
https://www.dropbox.com/s/3ia00ys75u6xwyy/Screenshot%202016-01-21%2006.35.01.png?dl=0

Here is the output when running the program:
2016-01-21 06:30:23.964 TankFinity[15396:659322] Apache Cordova native platform version 3.9.2 is starting.
2016-01-21 06:30:23.965 TankFinity[15396:659322] Multi-tasking -> Device: YES, App: YES
2016-01-21 06:30:23.966 TankFinity[15396:659322] Unlimited access to network resources
2016-01-21 06:30:23.969 TankFinity[15396:659322] 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file

2016-01-21 06:30:24.625 TankFinity[15396:659322] Resetting plugins due to page load.
2016-01-21 06:30:24.852 TankFinity[15396:659322] Finished load of: file:///Users/nitzanwilnai/Library/Developer/CoreSimulator/Devices/1F8D9352-4770-4C26-B90E-C04A793A88B1/data/Containers/Bundle/Application/3EF199C6-74FC-41A5-A857-CF0F1A5D92A8/TankFinity.app/www/index.html

**Comment by blakgeek** [comment]
Can you verify that Cordova updated the cordova_plugins.js file properly (see screen shot)?  I've run into issues with that file in the past for other plugins.  If the file is missing or not up to date, running `cordova prepare ios` solves the issue.
![screen shot 2016-01-21 at 4 03 29 pm](https://cloud.githubusercontent.com/assets/824542/12494578/0516e8e6-c059-11e5-8230-4215ac3d9179.png)

You can look at the [demo project](https://github.com/blakgeek/cordova-plugin-flurryanalytics-demo) for a simple reference as well.

Let me know if you're still having issues.

**Comment by nitzanwilnai** [comment]
I figured it out! It turns out I forgot to include the cordova.js file in the index.html file for this project. Including the cordova.js file fixed the problem!

**Comment by blakgeek** [comment]
Cool.  I'll close this then.
