### ISSUE TITLE
Event Parameters not being logged

### ISSUE THREAD

**Issue by franciswagner** [blakgeek/cordova-plugin-flurryanalytics#12]
Hi, I am using the following code, but the parameters are not being recorded. The event itself is ok,  I am able to see it on the flurry dashboard, but no parameters.

var flurryParams = {
  check: 'ok',
  active: true
};

flurryAnalytics.logEvent('Initialize', flurryParams, function() {
  console.log('Flurry Analytics event logged successfully');
}, function(err) {
  console.log(['Flurry Analytics event no logged. Error:', err]);
});

Thanks in advance,
Francis

**Comment by lakshaydulani** [comment]
You should be able to see the params after about 2 days of recording the event.
Mine event has only one parameter and it shows perfectly.
