### ISSUE TITLE
Invalid flurry lib name

### ISSUE THREAD

**Issue by egkozlov** [blakgeek/cordova-plugin-flurryanalytics#14]
Please change the name of flurry jar.
It should be "libs/FlurryAnalytics-6.0.0.jar"
https://github.com/blakgeek/cordova-plugin-flurryanalytics/blob/7438dc9586bcccace56690b9c4007ee7efe0c92f/src/android/flurryAnalytics.gradle

**Comment by blakgeek** [comment]
This should be fixed in the latest release v1.2.0
