### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by domwoe** [blakgeek/cordova-plugin-flurryanalytics#2]
I'm trying to use the plugin as part of an ionic app. I don't get any errors and the success callbacks are fired but nothing arrives at flurry.com. Not even a sessions started event.

How would you debug that problem?

Thanks a lot!

**Comment by domwoe** [comment]
I tested with the simulator and didn't press the home button. Now sessions arrive at Flurry. But no events...

**Comment by blakgeek** [comment]
I know this is old and you've probably already figured it out but in case
not,  the events in flurry are not real-time.  They can be delayed as long
24 hours I believe.

On Wed, Feb 4, 2015 at 3:10 AM, Dominic Wörner notifications@github.com
wrote:

> I tested with the simulator and didn't press the home button. Now sessions
> arrive at Flurry. But no events...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blakgeek/cordova-plugin-flurryanalytics/issues/2#issuecomment-72806895
> .

## 

Check out my games on www.bggamecentral.com or download them from the App
Stores
https://itunes.apple.com/us/artist/henry-lawton/id895605107
[image: Get it on Google Play]
https://play.google.com/store/apps/developer?id=BG+Games
