### ISSUE TITLE
Can´t send a logEvent

### ISSUE THREAD

**Issue by scrakcho** [blakgeek/cordova-plugin-flurryanalytics#23]
Installing the plugin, adding the module and prepare it in app.components.ts whith this code:
` const options: FlurryAnalyticsOptions = {`
`        appKey: 'YYGFKS44WD7WJXJYWBFB', `
`        reportSessionsOnClose: true,`
`        enableLogging: true`
`      };`
`      let fa: FlurryAnalyticsObject = this.flurryAnalytics.create(options);`
`      fa.startSession();//This is optional`
`      fa.logEvent('acceso_contenidoes', {nombre_contenido:'Recomendado y Ampliado'})`
`          .then(() => console.log('Logged an event!'))`
`          .catch(e => console.log('Error logging the event', e));`

This erros occurs...

Error logging the event kFlurryEventFailed (about logEvent)
ERROR message: "Uncaught (in promise): Invalid Action: startSession" (about startSession)

**Comment by blakgeek** [comment]
There's no need to call startSession, it has been removed from the Flurry.  I'll remove it from the plugin in the next release.
