### ISSUE TITLE
npm ERR! 404  'cordova-plugin-flurry-analytics' is not in the npm registry.

### ISSUE THREAD

**Issue by Reactor13** [blakgeek/cordova-plugin-flurryanalytics#30]
Hi,

Something is wrong with installing the plugin.
After plugin install 
_$ cordova plugin add cordova-plugin-flurryanalytics

in file confog.xml added:
<plugin name="cordova-plugin-flurry-analytics" spec="~1.4.4" />

in package.json after build:
"cordova-plugin-flurryanalytics": "^1.4.4",
"cordova-plugin-flurry-analytics": "~1.4.4"

any npm commands (like npm outdated) then non working with error:
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-flurry-analytics
npm ERR! 404 
npm ERR! 404  'cordova-plugin-flurry-analytics' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

If a remove "cordova-plugin-flurry-analytics": "~1.4.4" from package.json, this will be automatic recreated after next build.

How it fix correctly?

**Comment by ana-ya** [comment]
I have the same issue. They change the name of the plugin. Try to use 'cordova plugin add cordova-plugin-flurryanalytics@~1.4.4'

**Comment by Reactor13** [comment]
yes - it's.
But after each building the plugin name in package.json will be again cordova-plugin-flurry-analytics.

It's very annoying.

**Comment by Reactor13** [comment]
It seems, that in version 1.4.6 this issue has been fixed.
Great!
